# Generated by Django 6.0.2 on 2026-02-21 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id_veiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('quantidade_passageiros', models.PositiveIntegerField()),
                ('km_inicial', models.PositiveIntegerField(default=0)),
                ('kms_atual', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-id_veiculo'],
            },
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='vehicles.veiculo')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
