# Generated by Django 6.0.2 on 2026-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id_motorista', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo_carteira', models.CharField(choices=[('A', 'A - Motocicleta'), ('B', 'B - Carro'), ('C', 'C - Caminhão'), ('D', 'D - Ônibus'), ('E', 'E - Carreta')], max_length=1)),
            ],
            options={
                'ordering': ['-id_motorista'],
            },
        ),
    ]
