# Generated by Django 6.0.2 on 2026-02-21 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim_prevista', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada'), ('Concluida', 'Concluída'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20)),
                ('quantidade_passageiros', models.PositiveIntegerField(default=1)),
                ('observacao', models.TextField(blank=True, default='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='vehicles.motorista')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='vehicles.veiculo')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
