# Generated by Django 6.0.2 on 2026-02-21 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_solicitacaomotorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaomotorista',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='vehicles.motorista'),
        ),
    ]
