# Generated by Django 6.0.2 on 2026-02-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_solicitacaomotorista_motorista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaomotorista',
            name='quantidade_passageiros',
        ),
        migrations.RemoveField(
            model_name='solicitacaomotorista',
            name='veiculo',
        ),
    ]
