# Generated by Django 6.0.2 on 2026-02-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_remove_solicitacaomotorista_quantidade_passageiros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateTimeField()),
                ('data_fim_prevista', models.DateTimeField()),
                ('quantidade_passageiros', models.PositiveIntegerField()),
                ('local_embarque', models.CharField(max_length=200)),
                ('local_desembarque', models.CharField(max_length=200)),
                ('itinerario', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada'), ('Concluida', 'Concluída'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_viagem', to='vehicles.motorista')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_viagem', to='vehicles.veiculo')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
