# Generated by Django 6.0.2 on 2026-02-21 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_solicitacaoviagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPortaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_saida', models.PositiveIntegerField(blank=True, null=True)),
                ('km_chegada', models.PositiveIntegerField(blank=True, null=True)),
                ('horario_saida', models.DateTimeField(blank=True, null=True)),
                ('horario_chegada', models.DateTimeField(blank=True, null=True)),
                ('observacao_saida', models.TextField(blank=True, default='')),
                ('observacao_chegada', models.TextField(blank=True, default='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('viagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_portaria', to='vehicles.solicitacaoviagem')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
