# Generated by Django 6.0.2 on 2026-02-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_registroportaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
