# Generated by Django 6.0.2 on 2026-02-22 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_veiculo_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoviagem',
            name='motorista',
        ),
        migrations.AddField(
            model_name='solicitacaoviagem',
            name='solicitacao_motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagem', to='vehicles.solicitacaomotorista'),
        ),
    ]
